[package]
name = "rdf-owl-translator"
version = "0.1.0"
edition = "2024"

[dependencies]
dag-rdf = { path = "../dag_rdf" }
ingress = { path = "../ingress" }
owl-ontology = { path = "../owl_ontology" }
num-bigint = "0.5"
log = "0.4"
thiserror = "2"

[dev-dependencies]
turtle = { path = "../turtle" }
