#!/usr/bin/env bash
# Scaffold a provenance/summaries/pr-<N>.ttl transcript summary (CLAUDE.md
# step 6b / issue #334): fills in the mechanical boilerplate (prefixes,
# PullRequest/AgentSession triples, real commit timestamps) and leaves a
# TODO placeholder for the actual distilled reasoning, which still has to
# be written by hand per docs/plans/TRANSCRIPT_SUMMARY_GUIDELINES.md.
#
# Run from inside the worktree/branch the PR is on:
#
#   cd .claude/worktrees/<branch>
#   bash ../../../scripts/new-provenance-summary.sh <PR#> <issue#> [<base-ref>]
#
# <base-ref> defaults to "main" — the ref the branch diverged from.
#
# After running, edit the generated file's summaryText/decisionPoint
# (marked TODO) before committing — the script does not write prose.

set -euo pipefail

if [ "$#" -lt 2 ]; then
  echo "usage: $0 <PR#> <issue#> [<base-ref>]" >&2
  exit 1
fi

pr="$1"
issue="$2"
base="${3:-main}"

repo_root="$(git rev-parse --show-toplevel)"
out="$repo_root/provenance/summaries/pr-${pr}.ttl"

if [ -e "$out" ]; then
  echo "refusing to overwrite existing $out" >&2
  exit 1
fi

title="$(gh pr view "$pr" --json title -q '.title')"
branch="$(git rev-parse --abbrev-ref HEAD)"

started="$(git log "${base}..HEAD" --format=%aI --reverse | head -1)"
ended="$(git log "${base}..HEAD" --format=%aI | head -1)"

if [ -z "$started" ] || [ -z "$ended" ]; then
  echo "no commits found on $branch since $base — check the base-ref argument" >&2
  exit 1
fi

session_id="pr${pr}"

cat > "$out" <<EOF
@prefix agp: <https://dagalog.dev/ns/agentprov#> .
@prefix bl: <https://dagalog.dev/ns/backlog#> .
@prefix ghissues: <https://github.com/daghovland/rdf-datalog/issues/> .
@prefix ghpull: <https://github.com/daghovland/rdf-datalog/pull/> .
@prefix prov: <http://www.w3.org/ns/prov#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix session: <https://dagalog.dev/ns/agentprov/session#> .

# PROSPECTIVE summary scaffold, generated by scripts/new-provenance-summary.sh.
# TODO: replace the placeholder summaryText/decisionPoint below with the
# actual distilled reasoning behind this PR before committing — see
# docs/plans/TRANSCRIPT_SUMMARY_GUIDELINES.md. Timestamps below are real
# (from \`git log ${base}..HEAD\` on branch ${branch}); everything else that
# isn't marked TODO can be left as-is.

ghpull:${pr} a bl:PullRequest, bl:WorkItem ;
    rdfs:label "${title}" ;
    bl:number ${pr} ;
    bl:state bl:Open ;
    bl:closesIssue ghissues:${issue} .

session:claudeSonnet5 a prov:SoftwareAgent ;
    rdfs:label "Claude Sonnet 5" .

session:${session_id} a agp:AgentSession ;
    prov:wasAssociatedWith session:claudeSonnet5 ;
    prov:used ghissues:${issue} ;
    prov:startedAtTime "${started}"^^xsd:dateTime ;
    prov:endedAtTime "${ended}"^^xsd:dateTime .

session:${session_id}Summary a agp:TranscriptSummary ;
    agp:summaryText "TODO: replace with a distilled paragraph (30-4000 chars) describing what issue #${issue} actually asked for, what was tried/rejected along the way, and why the final approach was chosen. Not a changelog of file edits — the reasoning, per TRANSCRIPT_SUMMARY_GUIDELINES.md." ;
    agp:reasoningFor ghpull:${pr} ;
    prov:wasGeneratedBy session:${session_id} ;
    prov:wasAttributedTo session:claudeSonnet5 .

# TODO: if there was a genuine fork in approach worth recording, uncomment
# and fill in; otherwise delete this block and the agp:decisionPoint line
# above it on the Summary resource.
#
# session:${session_id}Summary agp:decisionPoint session:${session_id}Decision .
#
# session:${session_id}Decision a agp:Decision ;
#     agp:summaryText "TODO: the approach actually taken (30-4000 chars)." ;
#     agp:alternative "TODO: the alternative considered and why it was rejected." .
EOF

echo "wrote $out"
echo "next: edit the TODO-marked summaryText (and decisionPoint, if applicable), then:"
echo "  git add provenance/summaries/pr-${pr}.ttl && git commit -m 'provenance: transcript summary for PR #${pr} (#${issue})'"
